# This file should contain all the record creation needed to seed the database with its default values.",
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).",
#"
# Examples:"
#"
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])"
#   Character.create(name: 'Luke', movie: movies.first)"

proverbs = ["Seize the day.",
 "Live and learn.",
 "Sound as a bell.",
 "To each his own.",
 "As hard as nails.",
 "As sick as a dog.",
 "Fresh as a daisy.",
 "For donkeys' ages.",
 "Silence is golden.",
 "As green as grass.",
 "Silence is golden.",
 "Easy come, easy go.",
 "As fit as a fiddle.",
 "Divide and conquer.",
 "Love sees no faults.",
 "By hook or by crook.",
 "Waste not, want not.",
 "Pride feels no pain.",
 "Patience is a virtue.",
 "Life begins at forty.",
 "You are what you eat.",
 "Call a spade a spade.",
 "No news is good news.",
 "Least talk most work.",
 "A cat has nine lives.",
 "Diamonds are forever.",
 "Let the buyer beware.",
 "Look before you leap.",
 "Clothes make the man.",
 "Look before you leap.",
 "You snooze, you lose.",
 "Confess and be hanged.",
 "Bad news travels fast.",
 "Accidents will happen.",
 "Still waters run deep.",
 "Tomorrow is a new day.",
 "More haste less speed.",
 "Every dog has its day.",
 "Let sleeping dogs lie.",
 "Everything has an end.",
 "First in best dressed.",
 "Confess and be hanged.",
 "Cold hands, warm heart.",
 "To eat one's heart out.",
 "Manners maketh the man.",
 "Charity begins at home.",
 "Better safe than sorry.",
 "Better late than never.",
 "The bigger, the better.",
 "True beauty lies within.",
 "Only the good die young.",
 "Beauty is but skin deep.",
 "To add insult to injury.",
 "Do as I say not as I do.",
 "It's all in a days work.",
 "Leave no stone unturned.",
 "Every man has his price.",
 "Forewarned is forearmed.",
 "Don't beat a dead horse.",
 "Do right and fear no man.",
 "Greediness burst the bag.",
 "Hunger is the best sauce.",
 "Don't go off half-cocked.",
 "Few words and many deeds.",
 "Like a fish out of water.",
 "Big fish eat little fish.",
 "He who hesitates is lost.",
 "Many drops make a shower.",
 "Business before pleasure.",
 "First come, first served.",
 "If the cap fits, wear it.",
 "He who hesitates is lost.",
 "Modulation in all things.",
 "The modem is the message.",
 "Windows will never cease.",
 "Appearances are deceptive.",
 "Out of sight, out of mind.",
 "Adversity flatters no man.",
 "Fortune favours the brave.",
 "All's well that ends well.",
 "Not in a month of Sundays.",
 "The wise shall understand.",
 "An elephant never forgets.",
 "Every path has its puddle.",
 "The beaten path is safest.",
 "Step by step one goes far.",
 "Beggars can't be choosers.",
 "Penny wise, pound foolish.",
 "Fore-warned is fore-armed.",
 "Ask and you shall receive.",
 "All's fair in love and war.",
 "Hatred is as blind as love.",
 "Do as you would be done by.",
 "A bully is always a coward.",
 "Brevity is the soul of wit.",
 "Home is where the heart is.",
 "Show a clean pair of heels.",
 "Many hands make light work.",
 "Too many irons in the fire.",
 "It's either all or nothing.",
 "Rome wasn't built in a day.",
 "Honesty is the best policy.",
 "Pride cometh before a fall.",
 "Many hands make light work.",
 "Blood is thicker than water.",
 "Don't blow your own trumpet.",
 "A miss is as good as a mile.",
 "Familiarity breeds contempt.",
 "Hall binks are oft sliddery.",
 "It never rains but it pours.",
 "A stitch in time saves nine.",
 "Innocent as a new born babe.",
 "Never cackle unless you lay.",
 "Strike while the iron's hot.",
 "Better to have than to wish.",
 "Fair exchange is no robbery.",
 "Rules are made to be broken.",
 "A miss is as good as a mile.",
 "Love levels all inequalities.",
 "Love makes a good eye squint.",
 "It's not over till it's over.",
 "Leave tomorrow till tomorrow.",
 "Another pot ! Try the teapot.",
 "Fair words butter no cabbage.",
 "A fool uttereth all his mind.",
 "Stop beating around the bush.",
 "He has enough who is content.",
 "He is rich that is satisfied.",
 "Nobody can serve two masters.",
 "The customer is always right.",
 "In one ear and out the other.",
 "Variety is the spice of life.",
 "The early bird gets the worm.",
 "Fax is stranger than fiction.",
 "What boots up must come down.",
 "Grief divided is made lighter.",
 "The best of friends must part.",
 "Love to live and live to love.",
 "You can't live on bread alone.",
 "Drink like a fish, water only.",
 "Ready money is ready medicine.",
 "Since before cocky was an egg.",
 "Take your wife's first advice.",
 "A change is as good as a rest.",
 "Four eyes are better than two.",
 "Two heads are better than one.",
 "All cats are grey in the dark.",
 "As you sow, so shall you reap.",
 "Make hay while the sun shines.",
 "A bad penny always comes back.",
 "Cheap is dear in the long run.",
 "You're never too old to learn.",
 "Home is where you hang your @.",
 "Love and a cough cannot be hid.",
 "An open door may tempt a saint.",
 "Too many cooks spoil the broth.",
 "Wisdom is better than strength.",
 "A bad workman blames his tools.",
 "An old fox need learn no craft.",
 "After the storm comes the calm.",
 "A spark can start a great fire.",
 "Little strokes fell great oaks.",
 "Lost time is never found again.",
 "In for a penny, in for a pound.",
 "Experience is the best teacher.",
 "Too many cooks spoil the broth.",
 "A closed mouth gathers no foot.",
 "Give credit where credit is due.",
 "Faint heart never won fair lady.",
 "The Lord loveth a cheerful liar.",
 "Persuasion is better than force.",
 "While there's life there's hope.",
 "Half a loaf is better than none.",
 "Actions speak louder than words.",
 "He who sings drives away sorrow.",
 "Many a true word spoken in jest.",
 "Self praise is no recomendation.",
 "If you can't help, don't hinder.",
 "It's an old dog for a hard road.",
 "The early bird catches the worm.",
 "A rolling stone gathers no moss.",
 "Better to go back than go wrong.",
 "Empty bags cannot stand upright.",
 "Every cloud has a silver lining.",
 "A penny saved is a penny earned.",
 "Little and often fill the purse.",
 "The hood does not make the monk.",
 "Actions speak louder than words.",
 "Never judge a book by its cover.",
 "Half a loaf is better than none.",
 "Nothing dries sooner than a tear.",
 "He who wronged you will hate you.",
 "The best things in life are free.",
 "The meek shall inherit the earth.",
 "Better to wear out than rust out.",
 "Cleanliness is next to Godliness.",
 "A bad excuse is better then none.",
 "It takes two to have an argument.",
 "Where there's smoke there's fire.",
 "Wisdom is the wealth of the wise.",
 "Needs must when the devil drives.",
 "His bark is louder than his bite.",
 "A short cut is often a wrong cut.",
 "Fall seven times. Stand up eight.",
 "A poor man is better than a liar.",
 "One today is worth two tomorrows.",
 "There is no honour among thieves.",
 "A good thing is soon snatched up.",
 "Hasty climbers have sudden falls.",
 "One false move may lose the game.",
 "Always in a hurry, always behind.",
 "Don't change horses in midstream.",
 "The second mouse gets the cheese.",
 "If it's not broken, don't fix it.",
 "The lights on, but nobodies home.",
 "The geek shall inherit the earth.",
 "Too many clicks spoil the browse.",
 "Old friends and old wine are best.",
 "A loveless life is a living death.",
 "Love does much but money does all.",
 "Marry in haste, repent at leisure.",
 "Spare the rod and spoil the child.",
 "Old friends and old wine are best.",
 "Empty vessels make the most sound.",
 "Empty barrels make the most noise.",
 "The hardest work is to do nothing.",
 "Birds of a feather flock together.",
 "Kill two birds with the one stone.",
 "Putting the cart before the horse.",
 "While the cats away the mice play.",
 "Best to bend it while it's a twig.",
 "Mighty oaks from tiny acorns grow.",
 "You have to crawl before you walk.",
 "A light purse makes a heavy heart.",
 "Money burns a hole in your pocket.",
 "If anything can go wrong, it will.",
 "We do not always gain by changing.",
 "Empty vessels make the most noise.",
 "There is no fool like an old fool.",
 "Ask no questions and hear no lies.",
 "The squeaky wheel gets the grease.",
 "Virtual reality is its own reward.",
 "A friend is easier lost than found.",
 "Memory is the treasure of the mind.",
 "Man is the head but woman turns it.",
 "Anger and hate hinder good counsel.",
 "Attack is the best form of defense.",
 "Conscience makes cowards of us all.",
 "Heavy givers are light complainers.",
 "Never let the sun set on thy wrath.",
 "Adversity and loss make a man wise.",
 "All things come to those that wait.",
 "He who laughs last, laughs longest.",
 "Up and down like a fiddler's elbow.",
 "An onion a day keeps everyone away.",
 "Don't bite the hand that feeds you.",
 "Grumbling makes the loaf no larger.",
 "His eyes are bigger than his belly.",
 "Angry words fan the fire like wind.",
 "Speak clearly, if you speak at all.",
 "You can't tell a book by its cover.",
 "Wise it is to comprehend the whole.",
 "A good reputation is a fair estate.",
 "Don't try kicking against the wind.",
 "The sleepy fox catches no chickens.",
 "The worst wheel always creaks most.",
 "You can't get blood out of a stone.",
 "Experience is the father of wisdom.",
 "He that pays last never pays twice.",
 "A good conscience is a soft pillow.",
 "Don't rely on the label on the bag.",
 "Where there's a will there's a way.",
 "A fool in a gown is none the wiser.",
 "You cannot lose what you never had.",
 "The pen is mightier than the sword.",
 "A friend in need is a friend indeed.",
 "To err is human, to forgive divine.",
 "Absence makes the heart grow fonder.",
 "The receiver is as bad as the thief.",
 "He who rises late must trot all day.",
 "It is no use crying over spilt milk.",
 "What can't be cured must be endured.",
 "Attack is the best means of defence.",
 "Out of the frying pan into the fire.",
 "The darkest hour is before the dawn.",
 "Hard work never did anyone any harm.",
 "Not to break is better than to mend.",
 "The devil finds work for idle hands.",
 "As is the gardener so is the garden.",
 "Useless as a screen door on a dunny.",
 "A little each day is much in a year.",
 "Always you are to be rich next year.",
 "Absence makes the fond heart wander.",
 "Great groups from little icons grow.",
 "Pentium wise, pen and paper foolish.",
 "A problem shared is a problem halved.",
 "Beauty is in the eye of the beholder.",
 "Distance makes the heart grow fonder.",
 "A man of straw needs a woman of gold.",
 "He that hurts another, hurts himself.",
 "Never let the sun set on angry heart.",
 "Open confession is good for the soul.",
 "Cut your coat according to the cloth.",
 "Procrastination is the thief of time.",
 "The longer you live the more you see.",
 "An apple a day keeps the doctor away.",
 "You can't unscramble a scrambled egg.",
 "Don't advertise: Tell it to a gossip.",
 "Necessity is the mother of invention.",
 "Diligence is the mother of good luck.",
 "Never look a gift horse in the mouth.",
 "Small faults indulged let in greater.",
 "The best cast at dice is not to play.",
 "Possession is nine tenths of the law.",
 "A fool and his money are soon parted.",
 "Cheerfulness smooths the road of life.",
 "A drowning man will clutch at a straw.",
 "Better late thrive than never do well.",
 "One picture is worth a thousand words.",
 "Different strokes for different folks.",
 "No wise man ever wishes to be younger.",
 "An idle man is the devil's playfellow.",
 "The leopard does not change his spots.",
 "All aren't hunters that blow the horn.",
 "The more you stir, the more it stinks.",
 "A point is the beginning of magnitude.",
 "It is easier to destroy than to build.",
 "Credit won by lying is quick in dying.",
 "Don't put all your eggs in one basket.",
 "Hasty judgements are generally faulty.",
 "One man's loss, is another man's gain.",
 "Peace begins just where ambition ends.",
 "Use not today what tomorrow will need.",
 "You can't teach an old dog new tricks.",
 "Don't byte off more than you can view.",
 "First impressions are the most lasting.",
 "A man is known by the company he keeps.",
 "A handsome shoe often pinches the foot.",
 "All promises are either broken or kept.",
 "One man's meat is another man's poison.",
 "Gossips are frogs, they drink and talk.",
 "A bird makes his nest little by little.",
 "Deeds are fruits, words are but leaves.",
 "Distance lends enhancement to the view.",
 "It is the first step that is difficult.",
 "Cut off one's nose to spite one's face.",
 "See nothing, say nothing, know nothing.",
 "The fool wanders, the wise man travels.",
 "The best things come in small packages.",
 "Winners never quit, quitters never win.",
 "The best things are not bought and sold.",
 "The course of love never did run smooth.",
 "A good friend is one's nearest relation.",
 "He bears misery best that hides it most.",
 "Never let the sun go down on your anger.",
 "Discretion is the better part of valour.",
 "You can't have your cake and eat it too.",
 "Keep your mouth shut and your eyes open.",
 "Say what you mean and mean what you say.",
 "One mans junk is another man's treasure.",
 "Everybody must row with the oars he has.",
 "There's no use in flogging a dead horse.",
 "Like looking for a needle in a haystack.",
 "Oaks may fall when reeds take the storm.",
 "It is better to be born lucky than rich.",
 "A little knowledge is a dangerous thing.",
 "The gods help them that help themselves.",
 "Advice when most needed is least heeded.",
 "One of these days is none of these days.",
 "Speak softly and carry a cellular phone.",
 "Wondrous is the strength of cheerfulness.",
 "As one door closes, another always opens.",
 "The nearer the bone the sweeter the meat.",
 "Wondrous is the strength of cheerfulness.",
 "The harder you work, the luckier you are.",
 "Curses, like chickens come home to roost.",
 "It's an ill bird that fouls its own nest.",
 "The golden age never was the present one.",
 "Fools rush in where angels fear to tread.",
 "He who won't be advised, can't be helped.",
 "The bigger they are the harder they fall.",
 "False friends are worse than open enemies.",
 "Grow angry slowly; there's plenty of time.",
 "Never quarrel with one's bread and butter.",
 "You made your bed, now you must lie in it.",
 "An eye for an eye and a tooth for a tooth.",
 "If wishes were horses, beggars would ride.",
 "The proof of the pudding is in the eating.",
 "The sun shines on both sides of the hedge.",
 "Give them an inch and they'll take a mile.",
 "Grow angry slowly, there's plenty of time.",
 "Every man is the architect of his destiny.",
 "Never spend your money before you have it.",
 "The love of money is the root of all evil.",
 "It's a poor job that can't carry one boss.",
 "Two cannot fall out if one does not choose.",
 "There is a thin line between love and hate.",
 "A wink is as good as a nod, to a blind man.",
 "If you lose your temper, don't look for it.",
 "To wait and be patient soothes many a pang.",
 "Bread never falls but on its buttered side.",
 "There's many a slip, twixt cup and the lip.",
 "Listen to the pot calling the kettle black.",
 "Nothing is ill said if it is not ill taken.",
 "Silence is less injurious than a bad reply.",
 "Talking comes by nature, silence by wisdom.",
 "Wisdom is neither inheritance nor a legacy.",
 "All work and no play makes Jack a dull boy.",
 "To scare a bird is not the way to catch it.",
 "What do you expect from a pig, but a grunt?",
 "Shake the hand before you plough the field.",
 "Don't cross the bridge till you come to it.",
 "If it's not broke, mess with it till it is.",
 "A friend to everybody is a friend to nobody.",
 "Be slow in choosing, but slower in changing.",
 "Hope for the best and prepare for the worst.",
 "What you eat today walks and talks tomorrow.",
 "You never know what you can do till you try.",
 "A bird in the hand is worth two in the bush.",
 "Don't count your chickens before they hatch.",
 "Sauce for the goose is sauce for the gander.",
 "A man's intentions seldom add to his income.",
 "Behind every great man stands a strong woman.",
 "It's an ill wind that blows no-one some good.",
 "You can't put an old head on young shoulders.",
 "No life can be dreary when work is a delight.",
 "A chain is no stronger than its weakest link.",
 "Good company on the road is the shortest cut.",
 "Don't throw the baby out with the bath-water.",
 "A hair on the head is worth two in the brush.",
 "We cannot erase the sad records from our past.",
 "Be not a baker if your head is made of butter.",
 "If at first you don't succeed, try, try again.",
 "A little body doth often harbour a great soul.",
 "Some of the best gifts come in small packages.",
 "If at first you don't succeed, try, try again.",
 "A burden in the bush is worth two in the hand.",
 "The family that prays together, stays together.",
 "Silence is an excellent remedy against slander.",
 "If a job is worth doing it is worth doing well.",
 "Nothing falls into the mouth of a sleeping fox.",
 "You can't make a silk purse out of a sow's ear.",
 "The best ground bears weeds as well as flowers.",
 "The longest journey begins with the first step.",
 "The longest way round is the sweetest way home.",
 "Do unto others as you would have them do to you.",
 "To look as if butter will not melt in his mouth.",
 "Don't cross your bridges until you come to them.",
 "From trivial things, great contests often arise.",
 "Desperate diseases must have desperate remedies.",
 "What's the good of home, if you are never in it?",
 "No man is worse for knowing the worst of himself.",
 "No one can be caught in places he does not visit.",
 "Little thieves are hanged, but great ones escape.",
 "The wise man is deceived once but the fool twice.",
 "Never test the depth of the water with both feet.",
 "Flattery is all right so long as you don't inhale.",
 "Love sought is good, but given unsought is better.",
 "Love with life is heaven; and life unloving, hell.",
 "If you don't say it you will not have to unsay it.",
 "A throne is only a bench covered in purple velvet.",
 "Never put off 'til tomorrow what you can do today.",
 "Don't count your chickens before they are hatched.",
 "It is lonesome in the saddle since the horse died.",
 "A good thing is all the sweeter when won with pain.",
 "Do not in an instant what an age cannot recompense.",
 "Damage suffered makes you knowing, but seldom rich.",
 "Change is inevitable, except from vending machines.",
 "The strongest memory is weaker than the palest ink.",
 "You aren't learning much when your lips are moving.",
 "There is no better looking-glass than an old friend.",
 "At a round table there's no dispute about the place.",
 "After dinner rest a while, after supper walk a mile.",
 "If you lie down with dogs, you'll get up with fleas.",
 "An injury is forgiven better than an injury revenged.",
 "He who drinks a little too much drinks much too much.",
 "Facts do not cease to exist because they are ignored.",
 "In the country of the blind, the one-eyed man is king.",
 "Temper is so good a thing that we should never lose it.",
 "A man too careful of danger lives in continual torment.",
 "Curiosity killed the cat; Satisfaction brought it back.",
 "What the eye doesn't see, the heart doesn't grieve over.",
 "He who fights and runs away, lives to fight another day.",
 "Once a task has first begun, never quit until it's done.",
 "If at first you don't succeed, skydiving is not for you.",
 "A wise man doesn't need advice, and a fool won't take it.",
  "Good wine ruins the purse, and bad wine ruins the stomach.",
 "It is better to be green and growing than ripe and rotten.",
 "Necessity is a hard nurse, but she raises strong children.",
 "Laugh and the world laughs with you. Cry and you cry alone.",
 "Those who don't learn from history are doomed to repeat it.",
 "The grass is always greener on the other side of the fence.",
 "A single penny fairly got is worth a thousand that are not.",
 "If you tell the truth, you don't have to remember anything.",
 "You can eat an elephant if you do it one mouthful at a time.",
 "You can lead a horse to water, but you can't make him drink.",
 "Better to have loved and lost, than to have never loved at all.",
 "Early to bed, early to rise, makes you healthy, wealthy and wise.",
 "Sticks and stones may break my bones but words will never hurt me.",
 "Before you meet the handsome prince you have to kiss a lot of toads.",
 "I am rubber and you are glue. Your words bounce off me and stick to you.",
]

proverbs.each do |proverb|
  Fortune.create(proverb: proverb)
end
